version: "3"
services:
    db:
        image: postgres
        environment: 
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: zelda_cookbook
        volumes:
             - sql:/var/lib/postgresql/data
             # Uses the default postgres PGDATA volume
    backend:
        build: /home/bynet17/Artyom/DevOps - Igor/zelda/zelda-cookbook-backend/
 #       ports:
 #           - "8000:3000"
        depends_on:
            - db

    frontend: 
        build: /home/bynet17/Artyom/DevOps - Igor/zelda/zelda-cookbook-frontend/
        ports:
            - "80:80"
            - "8000:8000"
        depends_on:
            - backend
volumes:
    sql:

    
    
   
        

        
