version: "3"
services:
    db:
        image: postgres
        environment: 
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: zelda_cookbook
    backend:
        build: /home/bynet17/Artyom/DevOps - Igor/zelda/zelda-cookbook-backend/
        ports:
            - "8000:3000"
        depends_on:
            - db

    frontend: 
        build: /home/bynet17/Artyom/DevOps - Igor/zelda/zelda-cookbook-frontend/
        ports:
            - "3001:3000"

        
